"""Token usage model.

Implements the "Token Usage Tracker" component (SDD §4): records
prompt/completion/total token counts for every LLM-consuming operation,
either query answering (context_type="query", context_id=Answer.id) or
LLM Review (context_type="llm_review", context_id=Page.id).
"""

from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.enums import TokenUsageContextType


class TokenUsage(Base):
    """Audit record of tokens consumed by an LLM operation.

    Attributes:
        id: Surrogate primary key.
        user_id: Foreign key to the user whose operation consumed tokens.
        context_type: query (references Answer.id) or llm_review (references
            Page.id).
        context_id: Polymorphic reference — Answer.id for "query",
            Page.id for "llm_review".
        model_used: LLM model that consumed the tokens.
        prompt_tokens: Tokens in the prompt sent to the model.
        completion_tokens: Tokens generated by the model.
        total_tokens: prompt_tokens + completion_tokens.
        timestamp: When the usage occurred.
        user: The :class:`User` whose operation this records.
    """

    __tablename__ = "token_usage"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    context_type: Mapped[TokenUsageContextType] = mapped_column(
        Enum(TokenUsageContextType, values_callable=lambda e: [m.value for m in e]),
        nullable=False,
        index=True,
    )
    context_id: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
    model_used: Mapped[str] = mapped_column(String(128), nullable=False)
    prompt_tokens: Mapped[int] = mapped_column(Integer, nullable=False)
    completion_tokens: Mapped[int] = mapped_column(Integer, nullable=False)
    total_tokens: Mapped[int] = mapped_column(Integer, nullable=False)
    is_estimated: Mapped[bool] = mapped_column(sa.Boolean, default=False, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationship (string reference avoids circular imports)
    user: Mapped["User"] = relationship(back_populates="token_usage")  # noqa: F821