"""Query API routes (Phase 0 stubs).

Implements the "Backend API / Orchestrator" query endpoints (SDD §4).
POST /query is the core QA endpoint supporting both RAG Mode (retrieval +
LLM answer, Phase 7) and Raw Mode (LLM sees the original PDF directly,
Phase 8).
"""

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.schemas.answer import AnswerOut
from app.schemas.query import QueryCreate

router = APIRouter(prefix="/query", tags=["query"])


@router.post("", response_model=AnswerOut)
def ask_question(body: QueryCreate, db: Session = Depends(get_db)) -> AnswerOut:
    """Answer a natural-language question in RAG or Raw Mode.

    Realizes FR-24 (RAG Mode) and FR-26 (Raw Mode) — see Phases 7 and 8.

    Args:
        body: The question, mode, and optional k_value override.
        db: Database session (unused by the stub).

    Returns:
        A stub answer marked as fake.
    """
    # TODO(Phase 7/8): orchestrate embedding + vector search (RAG) or direct
    # LLM call (Raw), record Query + Answer + TokenUsage rows.
    return AnswerOut(
        id=1,
        query_id=1,
        generated_text="[STUB] This is a fake answer generated by the Phase 0 skeleton.",
        source_chunk_ids=None if body.mode.value == "raw" else [1, 2, 3],
        llm_model_version="stub-model",
    )