"""add sub_index to chunks table

Revision ID: 24275d24704b
Revises: 5ad5b89bf151
Create Date: 2026-09-14 14:05:21.444387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24275d24704b'
down_revision: Union[str, None] = '5ad5b89bf151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_index', sa.Integer(), nullable=False))

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('extraction_method',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('native', 'ocr', 'llm_vision', 'ocr_failed', 'llm_review_failed', name='extractionmethod'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('extraction_method',
               existing_type=sa.Enum('native', 'ocr', 'llm_vision', 'ocr_failed', 'llm_review_failed', name='extractionmethod'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_column('sub_index')

    # ### end Alembic commands ###