"""initial schema (Phase 0): all SDD 7 tables

Revision ID: a82f7751c6dc
Revises: 
Create Date: 2026-09-13 18:04:44.407298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82f7751c6dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'awaiting_feedback', 'ready', 'discarded', 'failed', name='documentstatus'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('k_value', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('rag', 'raw', name='querymode'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queries_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_queries_user_id'), ['user_id'], unique=False)

    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.Enum('query', 'llm_review', name='tokenusagecontexttype'), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_usage_context_id'), ['context_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_context_type'), ['context_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_user_id'), ['user_id'], unique=False)

    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('source_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('llm_model_version', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_query_id'), ['query_id'], unique=True)

    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('initial_processing', 'awaiting_feedback', 'llm_review', 'approved', name='pagestatus'), nullable=False),
    sa.Column('extraction_method', sa.Enum('native', 'ocr', 'llm_vision', name='extractionmethod'), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('review_round', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_status'), ['status'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Enum('text', 'table', 'image', name='chunktype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('table_markdown', sa.Text(), nullable=True),
    sa.Column('image_caption', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'edited', 'rejected', name='chunkreviewstatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_review_status'), ['review_status'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Enum('positive', 'negative', name='feedbackrating'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_answer_id'), ['answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_query_id'), ['query_id'], unique=False)

    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embeddings_chunk_id'), ['chunk_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_chunk_id'))

    op.drop_table('embeddings')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_query_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_answer_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_review_status'))
        batch_op.drop_index(batch_op.f('ix_chunks_page_id'))

    op.drop_table('chunks')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_status'))
        batch_op.drop_index(batch_op.f('ix_pages_document_id'))

    op.drop_table('pages')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_query_id'))

    op.drop_table('answers')
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_context_type'))
        batch_op.drop_index(batch_op.f('ix_token_usage_context_id'))

    op.drop_table('token_usage')
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queries_user_id'))
        batch_op.drop_index(batch_op.f('ix_queries_mode'))

    op.drop_table('queries')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))

    op.drop_table('documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###